baseURL = "http://blog.yeah.net.co/"
appendPort = false
languageCode = "en"

title = "rk074's"
author = "rk074"
copyright = "Except where otherwise noted, content on this site is licensed under a Creative Commons Attribution 3.0 License."

theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = ""
# googleAnalytics = ""
enableRobotsTXT = true
enableEmoji = true

[params]
  author = "rk074"
  description = "programming, video game, etc."

  dateformat = "Mon Jan 2 15:04:05, 2006"

  themeColor = "theme-base-0d"
  highlightjs = true
  # highlightjsstyle = "agate"
  # highlightjsstyle = "androidstudio"
  # highlightjsstyle = "atom-one-dark"
  # highlightjsstyle = "atom-one-light"
  # highlightjsstyle = "dracula"
  # highlightjsstyle = "darcula"
  # highlightjsstyle = "github"
  # highlightjsstyle = "hybrid"
  highlightjsstyle = "monokai"
  # highlightjsstyle = "ocean"
  # highlightjsstyle = "railscasts"
  # highlightjsstyle = "rainbow"
  # highlightjsstyle = "sunburst"
  # highlightjsstyle = "tomorrow-night"
  # highlightjsstyle = "tomorrow-night-bright"
  # highlightjsstyle = "tomorrow-night-eighties"
  # highlightjsstyle = "zenburn"

  # layoutReverse = false
  # relatedPosts = false
  # postNavigation = false

  # mainSections = ["post"]
[params.social]
  github = "nbitmage"
  # instagram = ""
  # medium = ""
  # bitbucket = ""
  # linkedin = ""
  twitter = "octarect"
  # keybase = ""
  facebook = "ryo.alter"
  # gitlab = ""
  # stackoverflow = ""
  # xing = ""
  email = "ryota.kota@member.fsf.org"

[params.meta]
  description = "blog written by octarect(Ryota Kota). programming, technology, video game"
  keywords = "blog,programming,technology"
